#!/usr/bin/env bash

while getopts "rsc" arg; do
	case $arg in
		r)
		docker run --name basedatos -e MYSQL_ROOT_PASSWORD=claveroot \
			-e MYSQL_USER=amigosuser \
			-e MYSQL_DATABASE=amigosdb \
			-e MYSQL_PASSWORD=amigospass \
			-v $(pwd)/basedatos:/var/lib/mysql \
			--rm --network pruebas -d mariadb
			;;
		s)
			docker stop basedatos
			;;
		c)
			docker ps
			;;
	esac
done


